# Dependencies
# kramdown:
#  input: GFM
#markdown: redcarpet

highlighter: rouge

#:         true

# Permalinks
permalink:        pretty

# Setup
title:            The CITE Architecture
tagline: Technology-independent, machine-actionable citation of scholarly resources
description:      'Web site for citation standards, implementations of standards, and supporting tools'
paginate_path: "/reviews/page:num"
url:
#baseurl: 'http://cite-architecture.github.io/'
baseurl: ''

author:
  name:           'Neel Smith'

paginate:         5


# Links:
links:
  - title: News
    url: /news
